user_types:
  Light:
    price_threshold: 4.0
    price_elasticity: 1.8
    decay_factor: 0.08
    usage_high: 5.0
    usage_low: 1.0

  Medium:
    price_threshold: 6.5
    price_elasticity: 1.2
    decay_factor: 0.1
    usage_high: 8.0
    usage_low: 2.5

  Heavy:
    price_threshold: 9.0
    price_elasticity: 0.8
    decay_factor: 0.12
    usage_high: 15.0
    usage_low: 5.0