q_learning:
  learning_rate: 0.1
  discount_factor: 0.9
  epsilon_start: 0.9
  epsilon_min: 0.01
  epsilon_decay: 0.995
  delta_actions: [-0.05, 0, 0.05]
  min_price: 3.0
  state_categories: 60
  model_path: "./data/trained_model/q_table.pkl"